export const alumni = [
  {
    name: "Frances Welsh",
    title: "Graduate Student",
    program: "MCB",
    start: "2019",
    end: "2024",
    currentPosition: "Research Scientist at Amazon",
  },
  {
    name: "David Bacsik",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2017",
    end: "2023",
    currentPosition: "Finishing medical school",
  },
  {
    name: "Lauren Gentles",
    title: "Graduate Student",
    program: "Microbiology",
    start: "2016",
    end: "2022",
    currentPosition: "Scientist III at Thermo Fisher Scientific",
  },
  {
    name: "Allie Greaney",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2016",
    end: "2022",
    currentPosition: "Internal medicine resident at UCSF",
  },
  {
    name: "Kate Crawford",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2017",
    end: "2021",
    currentPosition: "Laboratory Medicine and Pathology resident at UW",
  },
  {
    name: "Sarah Hilton",
    title: "Graduate Student",
    program: "Genome Sciences",
    start: "2016",
    end: "2020",
    currentPosition: "Senior Scientist at Dyno Therapeutics",
  },
  {
    name: "Adam Dingens",
    title: "Graduate Student",
    program: "Graduate Student (2015-2019), Research Scientist (2019-2020)",
    start: "2015",
    end: "2019",
    currentPosition: "Director building a 'stealth mode' biotech company",
  },
  {
    name: "Katherine Xue",
    title: "Graduate Student",
    program: "Genome Sciences",
    start: "2015",
    end: "2019",
    currentPosition:
      "Incoming assistant professor at the University of California, Irvine",
  },
  {
    name: "Juhye Lee",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2015",
    end: "2019",
    currentPosition: "Resident at Massachusetts General Hospital",
  },
  {
    name: "Heather Machkovech",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2014",
    end: "2018",
    currentPosition:
      "Internal Medicine resident at University of Wisconsin Hospital and Clinic",
  },
  {
    name: "Hugh Haddox",
    title: "Graduate Student",
    program: "MCB",
    start: "2013",
    end: "2017",
    currentPosition: "Project Manager in Erick Matsen's lab at Fred Hutch",
  },
  {
    name: "Mike Doud",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2013",
    end: "2017",
    currentPosition: "Infectious Disease Fellow at UC San Diego Health",
  },
  {
    name: "Kathryn Hooper",
    title: "Graduate Student",
    program: "MCB",
    start: "2012",
    end: "2015",
    currentPosition: "Senior Scientist at Sonoma Biotherapeutics",
  },
  {
    name: "Tal Einav",
    title: "Postdoc",
    start: "2019",
    end: "2023",
    currentPosition:
      "Assistant Professor at the La Jolla Institute of Immunology in San Diego",
  },
  {
    name: "Tyler Starr",
    title: "Postdoc",
    start: "2018",
    end: "2023",
    currentPosition: "Assistant Professor at the University of Utah",
  },
  {
    name: "Karen Barnard",
    title: "Postdoc",
    start: "2020",
    end: "2021",
    currentPosition: "Senior Medical Writer at Pfizer",
  },
  {
    name: "Alistair Russell",
    title: "Postdoc",
    start: "2014",
    end: "2019",
    currentPosition:
      "Assistant Professor at UCSD Division of Biological Sciences",
  },
  {
    name: "Shirleen Soh",
    title: "Postdoc",
    start: "2015",
    end: "2019",
    currentPosition:
      "Head of Academic Research at National Research Foundation, Singapore",
  },
  {
    name: "Jeremy Roop",
    title: "Postdoc",
    start: "2016",
    end: "2019",
    currentPosition: "Scientist at Berkeley Brewing Science",
  },
  {
    name: "Orr Ashenberg",
    title: "Postdoc",
    start: "2013",
    end: "2017",
    currentPosition:
      "Associate Director, Computational Biology at Broad Institute of MIT and Harvard",
  },
  {
    name: "Baragvi Thyagarajan",
    title: "Postdoc",
    start: "2011",
    end: "2014",
    currentPosition:
      "Scientific Project Manager at th Allen Institute for Brain Science",
  },
  {
    name: "Ariana Farrell",
    title: "Staff Member",
    start: "2020",
    end: "2023",
    currentPosition:
      "Incoming PhD student at UW Molecular and Cellular Biology",
  },
  {
    name: "Rosario Tarabi",
    title: "Staff Member",
    start: "2020",
    end: "2024",
    currentPosition:
      "Business student at Franciscan University of Steubenville",
  },
  {
    name: "Rachel Eguia",
    title: "Staff Member",
    start: "2019",
    end: "2021",
    currentPosition: "Associate Scientist at Variant Bio",
  },
  {
    name: "Keara Malone",
    title: "Staff Member",
    start: "2019",
    end: "2021",
    currentPosition: "Teaching English in Tochigi Prefecture, Japan",
  },
  {
    name: "Ian Gong",
    title: "Staff Member",
    start: "2011",
    end: "2014",
    currentPosition: "Assistant Facility Manager at Stop & Shop",
  },
  {
    name: "Jonathan Mah",
    title: "Undergraduate Researcher",
    start: "2018",
    end: "2020",
  },
  {
    name: "Cameron Meikle",
    title: "Undergraduate Researcher",
    start: "2018",
    end: "2018",
  },
  {
    name: "Noah Cassidy",
    title: "Undergraduate Researcher",
    start: "2017",
    end: "2018",
  },
  {
    name: "Jacob Kowalsky",
    title: "Undergraduate Researcher",
    start: "2016",
    end: "2018",
  },
  {
    name: "Alexandria Wilson",
    title: "Undergraduate Researcher",
    start: "2017",
    end: "2017",
  },
  {
    name: "Jai Padmakumar",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2016",
  },
  {
    name: "Lessane Ketema",
    title: "Undergraduate Researcher",
    start: "2016",
    end: "2016",
  },
  {
    name: "Alex Heckert",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2015",
  },
  {
    name: "Khrystyna Dilai",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Kendra Ferrier",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Brandon Pratt",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Donna Leet",
    title: "Undergraduate Researcher",
    start: "2012",
    end: "2013",
  },
  {
    name: "Ari Kaufman",
    title: "Undergraduate Researcher",
    start: "2013",
    end: "2013",
  },
  {
    name: "Sam Schetterer",
    title: "Undergraduate Researcher",
    start: "2011",
    end: "2012",
  },
];
