export const alumni = [
  {
    name: "Frances Welsh",
    title: "Graduate Student",
    program: "MCB",
    start: "2019",
    end: "2024",
    currentPosition: "Amazon",
  },
  {
    name: "David Bacsik",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2017",
    end: "2023",
    currentPosition: "Finishing medical school",
  },
  {
    name: "Graduate Student",
    title: "Graduate Student",
    program: "Microbiology",
    start: "2016",
    end: "2022",
    currentPosition:
      "Scientist III at Thermo Fisher Scientific, Cell Biology R&D",
  },
  {
    name: "Allie Greaney",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2016",
    end: "2022",
    currentPosition: "Internal medicine resident at UCSF",
  },
  {
    name: "Kate Crawford",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2017",
    end: "2021",
    currentPosition: "Pathology resident at UW",
  },
  {
    name: "Sarah Hilton",
    title: "Graduate Student",
    program: "Genome Sciences",
    start: "2016",
    end: "2020",
    currentPosition: "Data Scientist at bluebird bio",
  },
  {
    name: "Adam Dingens",
    title: "Research Scientist (2019-2020), Graduate Student (2015-2019)",
    program: "MCB",
    start: "2015",
    end: "2020",
    currentPosition: "Scientist in AAV Engineering at Shape Therapeutics",
  },
  {
    name: "Katherine Xue",
    title: "Graduate Student",
    program: "Genome Sciences",
    start: "2015",
    end: "2019",
    currentPosition:
      "James S. McDonnell Foundation Fellow at Stanford working with Dmitri Petrov and David Relman",
  },
  {
    name: "Juhye Lee",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2015",
    end: "2019",
    currentPosition: "?",
  },
  {
    name: "Heather Machkovech",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2014",
    end: "2018",
    currentPosition: "?",
  },
  {
    name: "Hugh Haddox",
    title: "Graduate Student",
    program: "MCB",
    start: "2013",
    end: "2017",
    currentPosition: "Matsen lab program manager",
  },
  {
    name: "Mike Doud",
    title: "Graduate Student",
    program: "MSTP and Genome Sciences",
    start: "2013",
    end: "2017",
    currentPosition: "Medical fellowship at UCSD",
  },
  {
    name: "Katie Hooper",
    title: "Graduate Student",
    program: "MCB",
    start: "2012",
    end: "2015",
    currentPosition:
      "Scientist in Translational Development at Sonoma Biotherapeutics",
  },
  {
    name: "Tal Einav",
    title: "Postdoc",
    start: "2019",
    end: "2023",
    currentPosition:
      "Assistant Professor at the La Jolla Institute of Immunology in San Diego",
  },
  {
    name: "Tyler Starr",
    title: "Postdoc",
    start: "2018",
    end: "2023",
    currentPosition: "Assistant Professor at the University of Utah",
  },
  {
    name: "Karen Barnard",
    title: "Postdoc",
    start: "2020",
    end: "2021",
    currentPosition: "Medical Writer at Seagen (Pfizer)",
  },
  {
    name: "Alistair Russell",
    title: "Postdoc",
    start: "2014",
    end: "2019",
    currentPosition: "Assistant Professor at UC San Diego",
  },
  {
    name: "Shirleen Soh",
    title: "Postdoc",
    start: "2015",
    end: "2019",
    currentPosition: "Senior Scientist at Merck in Singapore",
  },
  {
    name: "Jeremy Roop",
    title: "Postdoc",
    start: "2016",
    end: "2019",
    currentPosition: "Scientist at Berkeley Brewing Science",
  },
  {
    name: "Orr Ashenberg",
    title: "Postdoc",
    start: "2013",
    end: "2017",
    currentPosition:
      "Computational Biologist at the Klarman Cell Observatory of the Broad Institute",
  },
  {
    name: "Baragvi Thyagarajan",
    title: "Postdoc",
    start: "2011",
    end: "2014",
    currentPosition: "Scientific Officer at the HIV Vaccine Enterprise",
  },
  {
    name: "Ariana Farrell",
    title: "Research Technician",
    start: "2020",
    end: "2023",
    currentPosition: "Scientific Officer at the HIV Vaccine Enterprise",
  },
  {
    name: "Rachel Eguia",
    title: "Research Technician",
    start: "2019",
    end: "2021",
    currentPosition: "Associate Scientist at Century Therapeutics",
  },
  {
    name: "Keara Malone",
    title: "Research Technician",
    start: "2019",
    end: "2021",
    currentPosition: "Teaching English in Japan",
  },
  {
    name: "Cathy Lin",
    title: "Research Administrator",
    start: "2019",
    end: "2021",
    currentPosition: "Currently working at NOAA",
  },
  {
    name: "Ian Gong",
    title: "Lab Manager",
    start: "2011",
    end: "2014",
  },
  {
    name: "Jonathan Mah",
    title: "Undergraduate Researcher",
    start: "2018",
    end: "2020",
  },
  {
    name: "Cameron Meikle",
    title: "Undergraduate Researcher",
    start: "2018",
    end: "2018",
  },
  {
    name: "Noah Cassidy",
    title: "Undergraduate Researcher",
    start: "2017",
    end: "2018",
  },
  {
    name: "Jacob Kowalsky",
    title: "Undergraduate Researcher",
    start: "2016",
    end: "2018",
  },
  {
    name: "Alexandria Wilson",
    title: "Undergraduate Researcher",
    start: "2017",
    end: "2017",
  },
  {
    name: "Jai Padmakumar",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2016",
  },
  {
    name: "Lessane Ketema",
    title: "Undergraduate Researcher",
    start: "2016",
    end: "2016",
  },
  {
    name: "Alex Heckert",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2015",
  },
  {
    name: "Khrystyna Dilai",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Kendra Ferrier",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Brandon Pratt",
    title: "Undergraduate Researcher",
    start: "2014",
    end: "2014",
  },
  {
    name: "Donna Leet",
    title: "Undergraduate Researcher",
    start: "2012",
    end: "2013",
  },
  {
    name: "Ari Kaufman",
    title: "Undergraduate Researcher",
    start: "2013",
    end: "2013",
  },
  {
    name: "Sam Schetterer",
    title: "Undergraduate Researcher",
    start: "2011",
    end: "2012",
  },
  {
    name: "Libanos Redda",
    title: "High School Intern",
    start: "2012",
    end: "2012",
  },
];
